# rebuid by Manper

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-zmodem5800
PKG_VERSION:=1.2
PKG_RELEASE:=1

LUCI_TITLE:=LuCI for zmodem5800
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+kmod-usb-net +kmod-usb-core +kmod-usb-ohci +kmod-usb-serial +kmod-usb-serial-option +kmod-usb-uhci +kmod-usb2 +usb-modeswitch +usbutils


include $(TOPDIR)/feeds/luci/luci.mk

# $(eval $(call BuildPackage,luci-app-zmodem5800))
