# Copyright (C) Manper

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-modem-webui
PKG_VERSION:=1.4
PKG_RELEASE:=1

LUCI_TITLE:=LuCI for modemWebui
LUCI_PKGARCH:=all


include $(TOPDIR)/feeds/luci/luci.mk

# $(eval $(call BuildPackage,luci-app-modem-webui))
