#!/bin/sh /etc/rc.common

START=14
STOP=92

USE_PROCD=1

loop_atsd_tools() {
	local rule=$1
	procd_open_instance
	procd_set_param command /usr/bin/atsd_tools -i "$rule" 
	procd_set_param respawn 5 5 -1
	procd_close_instance
}


start_service() {
	config_load atsd_tools
	config_foreach  loop_atsd_tools channel
}
