# Copyright (C) Manper

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-ModemATSD
PKG_VERSION:=2.5
PKG_RELEASE:=1

LUCI_TITLE:=LuCI for ModemATSD
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# $(eval $(call BuildPackage,luci-app-ModemATSD))
