# Copyright (C) Manper

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-modemAK68
PKG_VERSION:=2.2
PKG_RELEASE:=1

LUCI_TITLE:=LuCI for modemAK68
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# $(eval $(call BuildPackage,luci-app-modemAK68))
