# Copyright (C) Manper

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-modem5800
PKG_VERSION:=1.2
PKG_RELEASE:=1

LUCI_TITLE:=LuCI for modem5800
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# $(eval $(call BuildPackage,luci-app-modem5800))
